name: TypeScript Linter and Deploy

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint TypeScript
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Run Linter
      run: npm run lint

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      # Add your deployment steps here, such as deploying to a server or cloud provider
      run: |
        # Example deployment command:
        # scp -r dist/* user@your-server:/path/to/destination
